// eslint-disable-next-line
export const LIST_ACTIONS = {
  SET_CHANNELS_LIST: 'SET_CHANNELS_LIST',
  SELECT_CHANNEL: 'SELECT_CHANNEL',
  POPULATE_CHANNEL_WITH_MESSAGES: 'POPULATE_CHANNEL_WITH_MESSAGES',
  ADD_MESSAGE: 'ADD_MESSAGE',
};
